name: Pull MongoDB Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pull-docker-image:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            network=host

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull MongoDB Image
        run: docker pull arm64v8/mongo:7.0.18
